pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: run-test
        build: test
        run: test

publish:
  blubberfile: blubber.yaml
  stages:
    - name: production
      build: production
      publish:
        image: true