name: GoKart

on:
  # schedule:
  #   - cron: "0 0 * * 0"
  # push:
  #   branches:
  #     - master
  #     - main
  # pull_request:
  #   branches:
  #     - master
  #     - main
  workflow_dispatch:

jobs:
  gokart:
    name: GoKart scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run GoKart
        uses: kitabisa/gokart-action@v1.0.0
        with:
          globalsTainted: true
          output: results.sarif

      - name: Upload GoKart results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
